name: Release Calculator

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Run tests
        run: python -m unittest discover -v 

      - name: Build exe with PyInstaller
        run: pyinstaller --onefile main.py --name calculator.exe

      - name: Build exe gui with PyInstaller
        run: pyinstaller --onefile calc_gui.py --name calculator_gui.exe

      - name: Build deb cli package from source
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo $VERSION
          mkdir -p deb_package/DEBIAN
          mkdir -p deb_package/usr/lib/calculator
          mkdir -p deb_package/usr/bin

          cp *.py deb_package/usr/lib/calculator/

          echo '#!/bin/bash' > deb_package/usr/bin/calculator
          echo 'python3 /usr/lib/calculator/main.py "$@"' >> deb_package/usr/bin/calculator
          chmod +x deb_package/usr/bin/calculator

          echo 'Package: calculator' > deb_package/DEBIAN/control
          echo "Version: $VERSION" >> deb_package/DEBIAN/control
          echo 'Section: utils' >> deb_package/DEBIAN/control
          echo 'Priority: optional' >> deb_package/DEBIAN/control
          echo 'Architecture: all' >> deb_package/DEBIAN/control
          echo 'Maintainer: Svetloe Pivo <svetloe@koronovonoe-pivo.ru>' >> deb_package/DEBIAN/control
          echo 'Description: Simple Python calculator' >> deb_package/DEBIAN/control

          dpkg-deb --build deb_package

      - name: Build deb GUI package from source
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo $VERSION
          mkdir -p deb_package_gui/DEBIAN
          mkdir -p deb_package_gui/usr/lib/calculator
          mkdir -p deb_package_gui/usr/bin

          cp *.py deb_package_gui/usr/lib/calculator/

          echo '#!/bin/bash' > deb_package_gui/usr/bin/calculator
          echo 'python3 /usr/lib/calculator/calc_gui.py "$@"' >> deb_package_gui/usr/bin/calculator
          chmod +x deb_package_gui/usr/bin/calculator

          echo 'Package: calculator-GUI' > deb_package_gui/DEBIAN/control
          echo "Version: $VERSION" >> deb_package_gui/DEBIAN/control
          echo 'Section: utils' >> deb_package_gui/DEBIAN/control
          echo 'Priority: optional' >> deb_package_gui/DEBIAN/control
          echo 'Architecture: all' >> deb_package_gui/DEBIAN/control
          echo 'Maintainer: Svetloe Pivo <svetloe@koronovonoe-pivo.ru>' >> deb_package_gui/DEBIAN/control
          echo 'Description: Simple Python calculator GUI' >> deb_package_gui/DEBIAN/control

          dpkg-deb --build deb_package_gui

      - name: Upload exe to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/calculator.exe
          asset_name: calculator.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload exe GUI to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/calculator_gui.exe
          asset_name: calculator_gui.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload CLI deb to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: deb_package.deb
          asset_name: calculator.deb
          asset_content_type: application/vnd.debian.binary-package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}


      - name: Upload GUI deb to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: deb_package_gui.deb
          asset_name: calculator_gui.deb
          asset_content_type: application/vnd.debian.binary-package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Clean build files
        run: |
          rm -rf build dist __pycache__ *.spec deb_package deb_package_gui

      - name: Build macOS CLI
        run: pyinstaller --onefile main.py --name calculator

      - name: Build macOS GUI
        run: pyinstaller --onefile --windowed calc_gui.py --name CalculatorGUI

      - name: tar.gz archive for CLI
        run: |
          mkdir -p release-macos
          cp dist/calculator release-macos/
          tar -czf calculator-macos.tar.gz -C release-macos .

      - name: tar.gz archive for GUI
        run: |
          mkdir -p release-macos-gui
          cp dist/CalculatorGUI release-macos-gui/
          tar -czf calculator-gui-macos.tar.gz -C release-macos-gui .

      - name: macOS Release CLI
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: calculator-macos.tar.gz
          asset_name: calculator-macos.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: macOS GUI to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: calculator-gui-macos.tar.gz
          asset_name: calculator-gui-macos.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
